// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package turso

import (
	"context"
	"reflect"

	"errors"
	"github.com/bchilcott/pulumi-turso/sdk/go/turso/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Database resource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/bchilcott/pulumi-turso/sdk/go/turso"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := turso.NewDatabase(ctx, "example", &turso.DatabaseArgs{
//				Group:            pulumi.String("a-group"),
//				OrganizationName: pulumi.String("an-organization"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import turso:index/database:Database example_database organization_name/database_name
// ```
type Database struct {
	pulumi.CustomResourceState

	// The database universal unique identifier (UUID).
	DbId pulumi.StringOutput `pulumi:"dbId"`
	// The name of the group where the database should be created. The group must already exist.
	Group pulumi.StringOutput `pulumi:"group"`
	// The DNS hostname used for client libSQL and HTTP connections.
	Hostname pulumi.StringOutput `pulumi:"hostname"`
	// Mark this database as the parent schema database that updates child databases with any schema changes.
	IsSchema pulumi.BoolPtrOutput `pulumi:"isSchema"`
	// The name of the new database. Must contain only lowercase letters, numbers, dashes. No longer than 32 characters.
	Name pulumi.StringOutput `pulumi:"name"`
	// Name of organization to create the database for
	OrganizationName pulumi.StringOutput `pulumi:"organizationName"`
	// The name of the parent database to use as the schema.
	Schema pulumi.StringPtrOutput `pulumi:"schema"`
	// The maximum size of the database in bytes. Values with units are also accepted, e.g. 1mb, 256mb, 1gb.
	SizeLimit pulumi.StringPtrOutput `pulumi:"sizeLimit"`
}

// NewDatabase registers a new resource with the given unique name, arguments, and options.
func NewDatabase(ctx *pulumi.Context,
	name string, args *DatabaseArgs, opts ...pulumi.ResourceOption) (*Database, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Group == nil {
		return nil, errors.New("invalid value for required argument 'Group'")
	}
	if args.OrganizationName == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Database
	err := ctx.RegisterResource("turso:index/database:Database", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDatabase gets an existing Database resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDatabase(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DatabaseState, opts ...pulumi.ResourceOption) (*Database, error) {
	var resource Database
	err := ctx.ReadResource("turso:index/database:Database", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Database resources.
type databaseState struct {
	// The database universal unique identifier (UUID).
	DbId *string `pulumi:"dbId"`
	// The name of the group where the database should be created. The group must already exist.
	Group *string `pulumi:"group"`
	// The DNS hostname used for client libSQL and HTTP connections.
	Hostname *string `pulumi:"hostname"`
	// Mark this database as the parent schema database that updates child databases with any schema changes.
	IsSchema *bool `pulumi:"isSchema"`
	// The name of the new database. Must contain only lowercase letters, numbers, dashes. No longer than 32 characters.
	Name *string `pulumi:"name"`
	// Name of organization to create the database for
	OrganizationName *string `pulumi:"organizationName"`
	// The name of the parent database to use as the schema.
	Schema *string `pulumi:"schema"`
	// The maximum size of the database in bytes. Values with units are also accepted, e.g. 1mb, 256mb, 1gb.
	SizeLimit *string `pulumi:"sizeLimit"`
}

type DatabaseState struct {
	// The database universal unique identifier (UUID).
	DbId pulumi.StringPtrInput
	// The name of the group where the database should be created. The group must already exist.
	Group pulumi.StringPtrInput
	// The DNS hostname used for client libSQL and HTTP connections.
	Hostname pulumi.StringPtrInput
	// Mark this database as the parent schema database that updates child databases with any schema changes.
	IsSchema pulumi.BoolPtrInput
	// The name of the new database. Must contain only lowercase letters, numbers, dashes. No longer than 32 characters.
	Name pulumi.StringPtrInput
	// Name of organization to create the database for
	OrganizationName pulumi.StringPtrInput
	// The name of the parent database to use as the schema.
	Schema pulumi.StringPtrInput
	// The maximum size of the database in bytes. Values with units are also accepted, e.g. 1mb, 256mb, 1gb.
	SizeLimit pulumi.StringPtrInput
}

func (DatabaseState) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseState)(nil)).Elem()
}

type databaseArgs struct {
	// The name of the group where the database should be created. The group must already exist.
	Group string `pulumi:"group"`
	// Mark this database as the parent schema database that updates child databases with any schema changes.
	IsSchema *bool `pulumi:"isSchema"`
	// The name of the new database. Must contain only lowercase letters, numbers, dashes. No longer than 32 characters.
	Name *string `pulumi:"name"`
	// Name of organization to create the database for
	OrganizationName string `pulumi:"organizationName"`
	// The name of the parent database to use as the schema.
	Schema *string `pulumi:"schema"`
	// The maximum size of the database in bytes. Values with units are also accepted, e.g. 1mb, 256mb, 1gb.
	SizeLimit *string `pulumi:"sizeLimit"`
}

// The set of arguments for constructing a Database resource.
type DatabaseArgs struct {
	// The name of the group where the database should be created. The group must already exist.
	Group pulumi.StringInput
	// Mark this database as the parent schema database that updates child databases with any schema changes.
	IsSchema pulumi.BoolPtrInput
	// The name of the new database. Must contain only lowercase letters, numbers, dashes. No longer than 32 characters.
	Name pulumi.StringPtrInput
	// Name of organization to create the database for
	OrganizationName pulumi.StringInput
	// The name of the parent database to use as the schema.
	Schema pulumi.StringPtrInput
	// The maximum size of the database in bytes. Values with units are also accepted, e.g. 1mb, 256mb, 1gb.
	SizeLimit pulumi.StringPtrInput
}

func (DatabaseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseArgs)(nil)).Elem()
}

type DatabaseInput interface {
	pulumi.Input

	ToDatabaseOutput() DatabaseOutput
	ToDatabaseOutputWithContext(ctx context.Context) DatabaseOutput
}

func (*Database) ElementType() reflect.Type {
	return reflect.TypeOf((**Database)(nil)).Elem()
}

func (i *Database) ToDatabaseOutput() DatabaseOutput {
	return i.ToDatabaseOutputWithContext(context.Background())
}

func (i *Database) ToDatabaseOutputWithContext(ctx context.Context) DatabaseOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseOutput)
}

// DatabaseArrayInput is an input type that accepts DatabaseArray and DatabaseArrayOutput values.
// You can construct a concrete instance of `DatabaseArrayInput` via:
//
//	DatabaseArray{ DatabaseArgs{...} }
type DatabaseArrayInput interface {
	pulumi.Input

	ToDatabaseArrayOutput() DatabaseArrayOutput
	ToDatabaseArrayOutputWithContext(context.Context) DatabaseArrayOutput
}

type DatabaseArray []DatabaseInput

func (DatabaseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Database)(nil)).Elem()
}

func (i DatabaseArray) ToDatabaseArrayOutput() DatabaseArrayOutput {
	return i.ToDatabaseArrayOutputWithContext(context.Background())
}

func (i DatabaseArray) ToDatabaseArrayOutputWithContext(ctx context.Context) DatabaseArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseArrayOutput)
}

// DatabaseMapInput is an input type that accepts DatabaseMap and DatabaseMapOutput values.
// You can construct a concrete instance of `DatabaseMapInput` via:
//
//	DatabaseMap{ "key": DatabaseArgs{...} }
type DatabaseMapInput interface {
	pulumi.Input

	ToDatabaseMapOutput() DatabaseMapOutput
	ToDatabaseMapOutputWithContext(context.Context) DatabaseMapOutput
}

type DatabaseMap map[string]DatabaseInput

func (DatabaseMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Database)(nil)).Elem()
}

func (i DatabaseMap) ToDatabaseMapOutput() DatabaseMapOutput {
	return i.ToDatabaseMapOutputWithContext(context.Background())
}

func (i DatabaseMap) ToDatabaseMapOutputWithContext(ctx context.Context) DatabaseMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseMapOutput)
}

type DatabaseOutput struct{ *pulumi.OutputState }

func (DatabaseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Database)(nil)).Elem()
}

func (o DatabaseOutput) ToDatabaseOutput() DatabaseOutput {
	return o
}

func (o DatabaseOutput) ToDatabaseOutputWithContext(ctx context.Context) DatabaseOutput {
	return o
}

// The database universal unique identifier (UUID).
func (o DatabaseOutput) DbId() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.DbId }).(pulumi.StringOutput)
}

// The name of the group where the database should be created. The group must already exist.
func (o DatabaseOutput) Group() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.Group }).(pulumi.StringOutput)
}

// The DNS hostname used for client libSQL and HTTP connections.
func (o DatabaseOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.Hostname }).(pulumi.StringOutput)
}

// Mark this database as the parent schema database that updates child databases with any schema changes.
func (o DatabaseOutput) IsSchema() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Database) pulumi.BoolPtrOutput { return v.IsSchema }).(pulumi.BoolPtrOutput)
}

// The name of the new database. Must contain only lowercase letters, numbers, dashes. No longer than 32 characters.
func (o DatabaseOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Name of organization to create the database for
func (o DatabaseOutput) OrganizationName() pulumi.StringOutput {
	return o.ApplyT(func(v *Database) pulumi.StringOutput { return v.OrganizationName }).(pulumi.StringOutput)
}

// The name of the parent database to use as the schema.
func (o DatabaseOutput) Schema() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Database) pulumi.StringPtrOutput { return v.Schema }).(pulumi.StringPtrOutput)
}

// The maximum size of the database in bytes. Values with units are also accepted, e.g. 1mb, 256mb, 1gb.
func (o DatabaseOutput) SizeLimit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Database) pulumi.StringPtrOutput { return v.SizeLimit }).(pulumi.StringPtrOutput)
}

type DatabaseArrayOutput struct{ *pulumi.OutputState }

func (DatabaseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Database)(nil)).Elem()
}

func (o DatabaseArrayOutput) ToDatabaseArrayOutput() DatabaseArrayOutput {
	return o
}

func (o DatabaseArrayOutput) ToDatabaseArrayOutputWithContext(ctx context.Context) DatabaseArrayOutput {
	return o
}

func (o DatabaseArrayOutput) Index(i pulumi.IntInput) DatabaseOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Database {
		return vs[0].([]*Database)[vs[1].(int)]
	}).(DatabaseOutput)
}

type DatabaseMapOutput struct{ *pulumi.OutputState }

func (DatabaseMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Database)(nil)).Elem()
}

func (o DatabaseMapOutput) ToDatabaseMapOutput() DatabaseMapOutput {
	return o
}

func (o DatabaseMapOutput) ToDatabaseMapOutputWithContext(ctx context.Context) DatabaseMapOutput {
	return o
}

func (o DatabaseMapOutput) MapIndex(k pulumi.StringInput) DatabaseOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Database {
		return vs[0].(map[string]*Database)[vs[1].(string)]
	}).(DatabaseOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseInput)(nil)).Elem(), &Database{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseArrayInput)(nil)).Elem(), DatabaseArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseMapInput)(nil)).Elem(), DatabaseMap{})
	pulumi.RegisterOutputType(DatabaseOutput{})
	pulumi.RegisterOutputType(DatabaseArrayOutput{})
	pulumi.RegisterOutputType(DatabaseMapOutput{})
}
