# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .database import *
from .database_token import *
from .get_database import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_turso.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_turso.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "turso",
  "mod": "index/database",
  "fqn": "pulumi_turso",
  "classes": {
   "turso:index/database:Database": "Database"
  }
 },
 {
  "pkg": "turso",
  "mod": "index/databaseToken",
  "fqn": "pulumi_turso",
  "classes": {
   "turso:index/databaseToken:DatabaseToken": "DatabaseToken"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "turso",
  "token": "pulumi:providers:turso",
  "fqn": "pulumi_turso",
  "class": "Provider"
 }
]
"""
)
